# Generated by Django 4.2.16 on 2024-11-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucak', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ucak',
            name='montaj_tamamlandi',
        ),
        migrations.AddField(
            model_name='ucak',
            name='montaj_sayisi',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
