# Generated by Django 4.2.16 on 2024-11-25 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcaTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, unique=True)),
                ('takim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parca_turleri', to='takim.takim')),
            ],
        ),
    ]
