# Generated by Django 4.2.16 on 2024-11-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parca', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parca',
            unique_together=set(),
        ),
    ]
