# Generated by Django 4.2.16 on 2024-11-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parca', '0002_alter_parca_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parca',
            name='geri_donusumde',
        ),
    ]
